### ISSUE TITLE
Can the “app” in the resource path not be mandatory? 

### ISSUE THREAD

**Issue by chenjiangshuo** [asticode/go-astilectron-bootstrap#12]
Is there any reasons to set the "app" in the resource path mandatory?

**Comment by asticode** [comment]
@chenjiangshuo if you're using the bootstrap, you need to use the `app` folder that will contain your html/css/js files. But if you do not wish to use the bootstrap which is totally possible, you don't need to add an `app` folder.

Does that answer your question?

**Comment by chenjiangshuo** [comment]
@asticode Okay, I got it. Thanks

**Comment by lthibault** [comment]
@asticode phew! It took me hours to debug this and end up here! 😃 

May I suggest posting this requirement conspicuously in the readme?  As a newcomer, it is not at all obvious!

Many thanks for this wonderful project!

Bien à vous,
Louis

**Comment by asticode** [comment]
@lthibault you're right, I've updated the README. Feel free to submit a PR if you feel the explanation is still not clear enough

**Comment by lthibault** [comment]
Great, thanks!
