### ISSUE TITLE
Strange behavior when configuring the default path

### ISSUE THREAD

**Issue by hitakiri** [asticode/go-astilectron-bootstrap#18]
For example: [code](https://github.com/Ghardo/astor/blob/master/example/main.go)
if compile it whith [bundler ](https://github.com/asticode/go-astilectron-bundler), the path for **index.html** in win7 is: file:///C:/Users/User/AppData/Roaming/AstorExample/resources/app/index.html

if i change params:
`Homepage: "./index.html" `
or
`BaseDirectoryPath: 	"./"`
Nothing changes.

How do I change the path configuration if I use **go-astilectron-bootstrap** ?

**Comment by asticode** [comment]
The logic that computes the data directory path is [here](https://github.com/asticode/go-astilectron/blob/master/paths.go#L93). As you can see, in windows7 there's an `APPDATA` environment variable that takes precedence over `BaseDirectoryPath` so this is normal that `BaseDirectoryPath: "./"` doesn't change anything.

I don't recommend setting a manual path when using the bundler (except when testing stuff) but if you really need it, use the [DataDirectoryPath](https://github.com/asticode/go-astilectron/blob/master/astilectron.go#L68) option. You `Homepage` should stay `index.html`

**Comment by hitakiri** [comment]
Thank you for clarification.
