### ISSUE TITLE
Return astilectron.Astilectron from bootstrap.Run function?

### ISSUE THREAD

**Issue by narup** [asticode/go-astilectron-bootstrap#3]
Thanks for this bootstrap. Any reason why Run function is not returning astilectron.Astilectron pointer? Could allow more customization on the caller side.

Thank

**Comment by asticode** [comment]
@narup the `Run` method is the blocking pattern therefore it never returns unless there's a fatal error. Hence it's not possible to return anything other than the error.

Nonetheless, you can retrieve `*astilectron.Astilectron` by using the `OnWait` option that allows you to store pointers to all valuable elements.

Does that answer your question?
