### ISSUE TITLE
Problems in using dev tools

### ISSUE THREAD

**Issue by apnerve** [asticode/go-astilectron-bootstrap#4]
It is difficult to use the dev tools as whenever we type `d`, it closes (hence cannot use any words that have the letter `d`).

Possible solution: Using <kbd>CTRL + d</kbd> or <kbd>CMD + d</kbd> or the default one as mentioned in [Chrome-devtools/shortcuts](https://developers.google.com/web/tools/chrome-devtools/shortcuts)

**Comment by asticode** [comment]
@apnerve this is a very good point indeed, juste updated the shortcut to "Control+d"
